cmake_minimum_required(VERSION 3.21)
project(IntervalCamera VERSION 1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Qt6 6.8 REQUIRED COMPONENTS Widgets Multimedia MultimediaWidgets)
add_executable(IntervalCamera WIN32 src/main.cpp src/camerawindow.cpp src/camerawindow.h)
target_link_libraries(IntervalCamera PRIVATE Qt6::Widgets Qt6::Multimedia Qt6::MultimediaWidgets)
